# Generated by Django 6.0.4 on 2026-04-29 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Fluxo')),
                ('status', models.CharField(choices=[('doc1_pending', 'Documento 1 Aguardando Assinatura'), ('doc2_pending', 'Documento 2 Aguardando Assinatura'), ('completed', 'Concluído')], default='doc1_pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Fluxo de Documentos',
                'verbose_name_plural': 'Fluxos de Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZapSignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Ordem')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('pdf_url', models.URLField(verbose_name='URL do PDF')),
                ('zapsign_token', models.CharField(blank=True, max_length=255, verbose_name='Token ZapSign')),
                ('status', models.CharField(choices=[('not_created', 'Não Enviado'), ('pending', 'Aguardando Assinatura'), ('signed', 'Assinado')], default='not_created', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentflow', verbose_name='Fluxo')),
            ],
            options={
                'verbose_name': 'Documento ZapSign',
                'verbose_name_plural': 'Documentos ZapSign',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('zapsign_token', models.CharField(blank=True, max_length=255, verbose_name='Token ZapSign')),
                ('sign_url', models.URLField(blank=True, verbose_name='Link de Assinatura')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('pending', 'Pendente'), ('signed', 'Assinado')], default='new', max_length=20, verbose_name='Status')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='documents.zapsigndocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Signatário',
                'verbose_name_plural': 'Signatários',
            },
        ),
    ]
