# Generated by Django 6.0.4 on 2026-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapsigndocument',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='zapsigndocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Arquivo PDF'),
        ),
    ]
