# Generated by Django 6.0.4 on 2026-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_zapsigndocument_signed_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapsigndocument',
            name='status',
            field=models.CharField(choices=[('not_created', 'Não Enviado'), ('pending', 'Aguardando Assinatura'), ('sent', 'Enviado'), ('signed', 'Assinado')], default='not_created', max_length=20, verbose_name='Status'),
        ),
    ]
